name: Retag on Hub
on: { workflow_dispatch: {} }

jobs:
  retag:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Copy manifest (rename)
        run: |
          set -eux
          docker buildx imagetools inspect xhzyz/captcha-solver:latest
          docker buildx imagetools create \
            --tag xhzyz/mars-ddddocr:latest \
            xhzyz/captcha-solver:latest
      - name: Verify new repo
        run: docker buildx imagetools inspect xhzyz/mars-ddddocr:latest
